
model:
  processes:
    A: 13
    B: 14
    C: 11
    D: 15
    E: 12
  intercepts:
    type: heterogeneous
    symbol: α
    distribution:
      name: rnorm
      args:
      - 1.5
      - 0.5
  covariates:
  - type: homogeneous
    variable:
      symbol: X1
      distribution:
        name: rexp
        args: 1.0
    coefficient:
      symbol: γ1
      distribution:
        name: rnorm
        args:
        - 0.2
        - 0.05
  - type: heterogeneous
    variable:
      symbol: X2
      distribution:
        name: rnorm
        args:
        - 0.0
        - 1.0
    coefficient:
      symbol: ζ2
      distribution:
        name: rnorm
        args:
        - 0.5
        - 0.1
  exposure:
    symbol: t
    distribution:
      name: runif
      args:
      - 2
      - 4
  weights:
    symbol: w
    distribution:
      name: runif
      args:
      - 1
      - 10
    normalize_mean_to: 1.0
  evaluation:
    mode: marginal
    reference:
      xstar:
        X1: 0.0
        X2: 0.0
    marginal:
      over: sample
      summary: mean
      n_mc: 1e6
optimization_specs:
  IL:
    step_size: 0.05
    fine_step_size: 0.025
    fine_window: 0.1
    num_std_errors:
    - -2.5
    - 6.0
    chunk_size: 4
    max_cores: 12
    num_workers: 12
  PL:
    step_size: 0.05
    fine_step_size: 0.025
    fine_window: 0.1
    alpha_levels:
    - 0.1
    - 0.05
    - 0.01

